### ISSUE TITLE
Modify the teams table

### ISSUE THREAD

**Issue by michael-beaver** [siggame/colisee-lib#10]
We need to add three more columns to the teams table in the database. They shouldn't affect any other tables.

- [x] a "salt" column that contains a string
- [x] a "hash_iterations" (or similar name) column that contains a number
- [x] a "role" column that can have the values ["user", "admin"]
- [x] a "contact_name" column that contains a string

Please let me know if there is anything else you need to know

**Comment by michael-beaver** [comment]
Just realized I left out the "contact_name" column, just edited it in to the main post

**Comment by user404d** [comment]
@michael-beaver forgot to ping you yesterday, but let me know if there are any issues
