### ISSUE TITLE
Add .toString() method for db interfaces

### ISSUE THREAD

**Issue by user404d** [siggame/colisee-lib#8]
A nice feature for when doing something like 
```js
const game: db.Game;
`${game}`
``` 
since it gets called implicitly.

**Comment by CoderOfTheLight** [comment]
Wrote a function that can be called for this job but still working on the implicit implementation. This is located in src/DB/index.ts

```
export function toString(thing){
    var output = '';
    for (var i in thing){
        output = output + i + ':' + thing[i] + '/n';
    }
    return output;
}
```

**Comment by user404d** [comment]
In the future, you should make a new branch to add a feature like this. Working off of master directly is not something that is encouraged when developing new/experimental features that haven't been vetted/tested yet.

**Comment by CoderOfTheLight** [comment]
Gotcha, sorry about that. I'll create a new branch for further modifications.

**Comment by user404d** [comment]
Outdated, db models need more work than just adding debugging representations
